import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

interface IBillions {
  id: string;
  name: string;
  squareImage: string;
  netWorth: number;
  industries: string[];
}

export default function Home() {
  const [billions, setBillions] = useState<IBillions[]>();

  const router = useRouter();

  const onClick = (id: string, title: string) => {
    router.push(
      {
        pathname: `/person/${id}`,
        query: {
          title,
          id,
        },
      },
      `/person/${id}`
    );
  };
  useEffect(() => {
    (async () => {
      const data = await fetch(
        `https://billions-api.nomadcoders.workers.dev/`
      ).then((res) => res.json());
      setBillions(data);
    })();
  }, []);

  return (
    <>
      <Head>
        <title>Billionare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#130f40] flex justify-center text-white">
        <div className="mt-20 max-w-7xl">
          <div className="grid grid-cols-4 gap-5">
            {billions?.map((item) => (
              <div
                key={item.id}
                onClick={() => {
                  onClick(item.id, item.name);
                }}
              >
                <div className="cursor-pointer">
                  <img src={item.squareImage} />
                </div>

                <Link
                  href={{
                    pathname: `/person/${item.id}`,
                    query: { title: item.name, id: item.id },
                  }}
                  as={`/person/${item.id}`}
                  legacyBehavior
                >
                  <a>
                    <div className="pt-4">
                      <span>{item.name}</span>
                    </div>
                    <div className="pt-1 pb-2">
                      <span>
                        {item.netWorth.toString().slice(0, 3)} Bliion /{" "}
                      </span>
                      <span>{item.industries}</span>
                    </div>
                  </a>
                </Link>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
